### ISSUE TITLE
Socks5Proxy and HostKey do not have dial timeout

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/socks5-proxy#10]
Whilst investigating https://github.com/cloudfoundry/bosh-cli/issues/432 the BOSH CLI hung indefinitely because the `Socks5Proxy` and `HostKey` do not set a `Timeout` in their `ssh.ClientConfig`.

Would you accept a PR to timeout after, say, 30 seconds?

Josh and @mirahimage

**Comment by cwlbraa** [comment]
yes
