### ISSUE TITLE
No released version

### ISSUE THREAD

**Issue by kirederik** [cloudfoundry/socks5-proxy#12]
Hi,

We use (indirectly) this repo in two dependencies (credhub-cli and bosh-utils) and we'd like to bump both to the latest version.

The problem is both depend on socks5-proxy and they have different constraints. 

Can we have a tagged version, so we can depend on a tag rather than on a revision?

Thanks

with @winnab

**Comment by zachgersh** [comment]
@kirederik - done :D apologies for the LONG delay on this.

https://github.com/cloudfoundry/socks5-proxy/releases/tag/v0.1.0
